import re
from .base_parser import BaseParser

class BehaviorParser(BaseParser):
    """Parser for behavior configuration"""
    
    def save_config(self, tab):
        """Save behavior configuration to input.kdl in KDL format"""
        content = '// Generated by niri-settings - Edits will be overwritten!\n\n'
        content += 'input {\n'
        
        if tab.warp_mouse_to_focus_checkbox.isChecked():
            content += '    warp-mouse-to-focus\n'
        else:
            content += '    // warp-mouse-to-focus\n'
            
        if tab.focus_follows_mouse_checkbox.isChecked():
            content += '    focus-follows-mouse\n'
        else:
            content += '    // focus-follows-mouse\n'
            
        if tab.disable_power_key_checkbox.isChecked():
            content += '    disable-power-key-handling\n'
        else:
            content += '    // disable-power-key-handling\n'
            
        if tab.workspace_auto_back_forth_checkbox.isChecked():
            content += '    workspace-auto-back-and-forth\n'
        else:
            content += '    // workspace-auto-back-and-forth\n'
            
        if tab.super_radio.isChecked():
            content += '    mod-key "Super"\n'
        elif tab.alt_radio.isChecked():
            content += '    mod-key "Alt"\n'
        elif tab.ctrl_radio.isChecked():
            content += '    mod-key "Ctrl"\n'
            
        self.write_to_file(content)
        
        # Append additional behavior settings
        additional_content = '    \n}\n\n'
        
        # Hot Key Overlay
        additional_content += 'hotkey-overlay {\n    hide-not-bound\n'
        if tab.hotkey_overlay_checkbox.isChecked():
            additional_content += '    // skip-at-startup\n'
        else:
            additional_content += '    skip-at-startup\n'
        additional_content += '    }\n\n'
        
        # Gestures
        additional_content += 'gestures {\n'
        additional_content += '    hot-corners {\n'
        if tab.hot_corners_checkbox.isChecked():
            additional_content += '        off\n'
        else:
            additional_content += '        // off\n'
        additional_content += '    }\n}\n\n'
        
        # Debug
        additional_content += 'debug {\n'
        if tab.focus_request_checkbox.isChecked():
            additional_content += '    honor-xdg-activation-with-invalid-serial \n'
        else:
            additional_content += '    // honor-xdg-activation-with-invalid-serial \n'
        additional_content += '}\n'
        
        # Cursor
        additional_content += 'cursor {\n'
        if tab.hide_while_typing_checkbox.isChecked():
            additional_content += '    hide-when-typing \n'
        else:
            additional_content += '    // hide-when-typing \n'
        if tab.inactive_enable_checkbox.isChecked():
            additional_content += f'    hide-after-inactive-ms {tab.inactive_spinbox.value()}\n'
        else:
            additional_content += f'    // hide-after-inactive-ms {tab.inactive_spinbox.value()}\n'
        additional_content += '}\n'
        
        # Screenshot path
        path = tab.screenshot_path_edit.text()
        if path:
            additional_content += f'\nscreenshot-path "{path}"\n'
            
        self.write_to_file(additional_content, 'a')
    
    def load_config(self, tab, content):
        """Load behavior configuration from content"""
        # Parse behavior settings
        tab.warp_mouse_to_focus_checkbox.setChecked(
            self.is_setting_enabled(content, 'warp-mouse-to-focus')
        )
        tab.focus_follows_mouse_checkbox.setChecked(
            self.is_setting_enabled(content, 'focus-follows-mouse')
        )
        tab.disable_power_key_checkbox.setChecked(
            self.is_setting_enabled(content, 'disable-power-key-handling')
        )
        tab.workspace_auto_back_forth_checkbox.setChecked(
            self.is_setting_enabled(content, 'workspace-auto-back-and-forth')
        )
        
        tab.hotkey_overlay_checkbox.setChecked(
            '// skip-at-startup' in content
        )
        
        tab.focus_request_checkbox.setChecked(
            self.is_setting_enabled(content, 'honor-xdg-activation-with-invalid-serial')
        )
        
        tab.hide_while_typing_checkbox.setChecked(
            self.is_setting_enabled(content, 'hide-when-typing')
        )
        
        tab.inactive_enable_checkbox.setChecked(
            self.is_setting_enabled(content, 'hide-after-inactive-ms')
        )
        
        # Parse inactive timeout value
        value = self.get_setting_value(content, r'hide-after-inactive-ms\s+(\d+)')
        if value:
            tab.inactive_spinbox.setValue(int(value))
        
        # Parse hot corners
        hot_corners_match = re.search(r'gestures\s*\{\s*hot-corners\s*\{[^}]*//[^}]*\}\s*\}', content)
        tab.hot_corners_checkbox.setChecked(not bool(hot_corners_match))
        
        # Parse screenshot path
        path = self.get_setting_value(content, r'screenshot-path\s+"([^"]+)"')
        if path:
            tab.screenshot_path_edit.setText(path)
        
        # Parse mod key
        try:
            mod_key = self.get_setting_value(content, r'mod-key\s+"([^"]+)"')
            if mod_key:
                if mod_key == "Super":
                    tab.super_radio.setChecked(True)
                elif mod_key == "Alt":
                    tab.alt_radio.setChecked(True)
                elif mod_key == "Ctrl":
                    tab.ctrl_radio.setChecked(True)
        except Exception as e:
            print(f"Error parsing mod-key: {e}")