import sys
import os
import re
import webbrowser
from PyQt6.QtWidgets import (QApplication, QMainWindow, QWidget, QVBoxLayout,
                             QHBoxLayout, QPushButton, QTabWidget, QStyle)
from PyQt6.QtCore import QTranslator, QLocale, QLibraryInfo
from PyQt6.QtGui import QIcon

from .conf_path import get_config_path
from .all_tabs import AppearanceTab, BehaviorTab ,TouchpadTab, MouseTab,KeyboardTab

class SettingsWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.config_path = get_config_path()
        self.init_ui()
        self.load_settings()

    def open_wiki(self):
        wiki_url = "https://yalter.github.io/niri/Configuration%3A-Input"
        webbrowser.open(wiki_url)

    def init_ui(self):
        self.setWindowTitle('Niri Settings')
        self.setFixedSize(600, 750)

        # Try to use system theme icon first, fallback to Qt standard icon
        icon = QIcon.fromTheme("preferences-desktop")
        if icon.isNull():
            icon = self.style().standardIcon(QStyle.StandardPixmap.SP_FileDialogDetailedView)
        self.setWindowIcon(icon)

        # Central widget
        central_widget = QWidget()
        self.setCentralWidget(central_widget)

        # Main layout
        main_layout = QVBoxLayout(central_widget)
        main_layout.setSpacing(20)
        main_layout.setContentsMargins(10, 10, 10, 10)

        # Create tab widget
        self.tabs = QTabWidget()

        # Create tabs
        self.appearance_tab = AppearanceTab(self)
        self.behavior_tab = BehaviorTab(self)
        self.touchpad_tab = TouchpadTab(self)
        self.mouse_tab = MouseTab(self)
        self.keyboard_tab = KeyboardTab(self)

        self.tabs.addTab(self.appearance_tab, self.tr("Appearance"))
        self.tabs.addTab(self.behavior_tab, self.tr("Behavior"))
        self.tabs.addTab(self.touchpad_tab, self.tr("Touchpad"))
        self.tabs.addTab(self.mouse_tab, self.tr("Mouse"))
        self.tabs.addTab(self.keyboard_tab, self.tr("Keyboard"))

        main_layout.addWidget(self.tabs)

        # Button layout
        button_layout = QHBoxLayout()

        wiki_btn = QPushButton(self.tr('Wiki'))
        wiki_btn.setFixedSize(80, 35)
        wiki_btn.clicked.connect(self.open_wiki)

        apply_btn = QPushButton(self.tr('Apply'))
        apply_btn.setFixedSize(120, 35)
        apply_btn.clicked.connect(self.apply_settings)

        close_btn = QPushButton(self.tr('Close'))
        close_btn.setFixedSize(120, 35)
        close_btn.clicked.connect(self.close)

        button_layout.addWidget(wiki_btn)
        button_layout.addStretch()
        button_layout.addWidget(apply_btn)
        button_layout.addWidget(close_btn)

        main_layout.addLayout(button_layout)

    def apply_settings(self):
        """Save settings to input.kdl in KDL format"""
        self.save_behavior_config()
        self.save_touchpad_config()
        self.save_mouse_config()
        self.save_keyboard_config()
        print(f"Settings applied to {self.config_path}")

    def save_behavior_config(self):
        """Save behavior and appearance configuration to input.kdl"""
        with open(self.config_path, 'w') as f:
            f.write('// Generated by niri-settings - Edits will be overwritten!\n\n')
            if self.appearance_tab.csd_checkbox.isChecked():
                f.write('// prefer-no-csd\n\n')
            else:
                f.write('prefer-no-csd\n\n')
            f.write('overview {\n')
            f.write(f'    zoom {self.appearance_tab.overview_spinbox.value()}\n')
            f.write('}\n\nanimations {\n')
            if self.appearance_tab.animations_enable_checkbox.isChecked():
                f.write('    on\n')
            else:
                f.write('    off\n')
            f.write(f'    slowdown {self.appearance_tab.animations_spinbox.value()}\n')

            # Layout block
            f.write('}\n\nlayout {\n')
            if self.appearance_tab.shadows_checkbox.isChecked():
                f.write('    shadow {\n    on\n    }')
            else:
                f.write('    shadow {\n    off\n    }')
            f.write(f'\n    gaps {self.appearance_tab.gaps_spinbox.value()}\n')

            f.write('\n    struts {\n')
            f.write(f'        left {self.appearance_tab.struts_left_spin.value()}\n')
            f.write(f'        right {self.appearance_tab.struts_right_spin.value()}\n')
            f.write(f'        top {self.appearance_tab.struts_top_spin.value()}\n')
            f.write(f'        bottom {self.appearance_tab.struts_bottom_spin.value()}\n')
            f.write('    }\n\n    focus-ring {\n')
            if self.appearance_tab.focus_ring_enable_checkbox.isChecked():
                f.write('        on\n')
            else:
                f.write('        off\n')
            f.write(f'        width {self.appearance_tab.focus_ring_spinbox.value()}\n')
            f.write(f'        active-color "{self.appearance_tab.current_color}"\n')

            f.write('    }\n\n    border {\n')
            if self.appearance_tab.border_enable_checkbox.isChecked():
                f.write('        on\n')
            else:
                f.write('        off\n')
            f.write(f'        width {self.appearance_tab.border_spinbox.value()
            }\n')
            f.write(f'        active-color "{self.appearance_tab.current_bordercolor}"\n')
            f.write('    }\n}\n')

            # Input block
            f.write(' \n\ninput {\n')
            if self.behavior_tab.warp_mouse_to_focus_checkbox.isChecked():
                f.write('    warp-mouse-to-focus\n')
            else:
                f.write('    // warp-mouse-to-focus\n')
            if self.behavior_tab.focus_follows_mouse_checkbox.isChecked():
                f.write('    focus-follows-mouse\n')
            else:
                f.write('    // focus-follows-mouse\n')
            if self.behavior_tab.disable_power_key_checkbox.isChecked():
                f.write('    disable-power-key-handling\n')
            else:
                f.write('    // disable-power-key-handling\n')
            if self.behavior_tab.workspace_auto_back_forth_checkbox.isChecked():
                f.write('    workspace-auto-back-and-forth\n')
            else:
                f.write('    // workspace-auto-back-and-forth\n')
            if self.behavior_tab.super_radio.isChecked():
                f.write('    mod-key "Super"\n')
            elif self.behavior_tab.alt_radio.isChecked():
                f.write('    mod-key "Alt"\n')
            elif self.behavior_tab.ctrl_radio.isChecked():
                f.write('    mod-key "Ctrl"\n')

    def save_touchpad_config(self):
        try:
            with open(self.config_path, 'a') as f:  # Append to the file
                f.write('    \n')
                f.write('    touchpad {\n')

                if self.touchpad_tab.tap_checkbox.isChecked():
                    f.write('        tap\n')
                else:
                    f.write('        // tap\n')
                if self.touchpad_tab.dwt_checkbox.isChecked():
                    f.write('        dwt\n')
                else:
                    f.write('        // dwt\n')
                if self.touchpad_tab.natural_scroll_checkbox.isChecked():
                    f.write('        natural-scroll\n')
                else:
                    f.write('        // natural-scroll\n')
                if self.touchpad_tab.drag_lock_checkbox.isChecked():
                    f.write('        drag-lock\n')
                else:
                    f.write('        // drag-lock\n')
                if self.touchpad_tab.disable_external_mouse_checkbox.isChecked():
                    f.write('        disabled-on-external-mouse\n')
                else:
                    f.write('        // disabled-on-external-mouse\n')
                if self.touchpad_tab.left_handed_checkbox.isChecked():
                    f.write('        left-handed\n')
                else:
                    f.write('        // left-handed\n')

                if self.touchpad_tab.no_scroll_radio.isChecked():
                    f.write('        scroll-method "no-scroll"\n')
                elif self.touchpad_tab.two_finger_radio.isChecked():
                    f.write('        scroll-method "two-finger"\n')
                elif self.touchpad_tab.edge_radio.isChecked():
                    f.write('        scroll-method "edge"\n')
                elif self.touchpad_tab.button_radio.isChecked():
                    f.write('        scroll-method "on-button-down"\n')

                # Always write those settings
                f.write(f'        accel-speed {self.touchpad_tab.accel_speed_spinbox.value()}\n')
                f.write(f'        accel-profile "{self.touchpad_tab.accel_profile_combobox.currentText()}"\n')
                f.write(f'        scroll-factor {self.touchpad_tab.scroll_factor_spinbox.value()}\n')
                f.write('    }\n')

        except Exception as e:
            print(f"Error saving touchpad configuration: {e}")

    def save_mouse_config(self):
        try:
            with open(self.config_path, 'a') as f:  # Append to the file
                f.write('    \n')
                f.write('    mouse {\n')
                if self.mouse_tab.natural_scroll_checkbox.isChecked():
                    f.write('        natural-scroll\n')
                else:
                    f.write('        // natural-scroll\n')
                if self.mouse_tab.left_handed_checkbox.isChecked():
                    f.write('        left-handed\n')
                else:
                    f.write('        // left-handed\n')
                if self.mouse_tab.middle_emulation_checkbox.isChecked():
                    f.write('        middle-emulation\n')
                else:
                    f.write('        // middle-emulation\n')

                # Always write those settings
                f.write(f'        accel-speed {self.mouse_tab.accel_speed_spinbox.value()}\n')
                f.write(f'        accel-profile "{self.mouse_tab.accel_profile_combobox.currentText()}"\n')
                f.write(f'        scroll-factor {self.mouse_tab.scroll_factor_spinbox.value()}\n')

                f.write('    }\n')

        except Exception as e:
            print(f"Error saving mouse configuration: {e}")

    def save_keyboard_config(self):
        """Save keyboard configuration to input.kdl in KDL format"""
        with open(self.config_path, 'a') as f:  # Append to the file
            f.write('    \n')
            f.write('    keyboard {\n')
            f.write(f'        track-layout "{self.keyboard_tab.track_layout_combobox.currentText()}"\n')
            if self.keyboard_tab.numlock_checkbox.isChecked():
                f.write('        numlock\n')
            else:
                f.write('        // numlock\n')
            f.write('        xkb {\n')
            f.write(f'           layout "{self.keyboard_tab.layout_edit.text()}"\n')
            f.write(f'           variant "{self.keyboard_tab.variant_edit.text()}"\n')
            f.write(f'           options "{self.keyboard_tab.options_edit.text()}"\n')
            f.write(f'           model "{self.keyboard_tab.model_edit.text()}"\n')
            f.write(f'           file "{self.keyboard_tab.file_edit.text()}"\n')
            f.write('        }\n')

            f.write(f'        repeat-delay {self.keyboard_tab.repeat_delay_spinbox.value()}\n')
            f.write(f'        repeat-rate {self.keyboard_tab.repeat_rate_spinbox.value()}\n')

            f.write('    }\n')
            f.write('}\n\n')

            # Behavior Tab: Hot Key Overlay
            f.write('hotkey-overlay {\n    hide-not-bound\n')
            if self.behavior_tab.hotkey_overlay_checkbox.isChecked():
                f.write('    // skip-at-startup\n')
            else:
                f.write('    skip-at-startup\n')
            f.write('    }\n\n')

            # Gestures
            f.write('gestures {\n')
            f.write('    hot-corners {\n')
            if self.behavior_tab.hot_corners_checkbox.isChecked():
                f.write('        off\n')
            else:
                f.write('        // off\n')
            f.write('    }\n}\n\n')

            # Debug
            f.write('debug {\n')
            if self.behavior_tab.focus_request_checkbox.isChecked():
                f.write('    honor-xdg-activation-with-invalid-serial \n')
            else:
                    f.write('    // honor-xdg-activation-with-invalid-serial \n')
            f.write('}\n\n')

            # Cursor
            f.write('cursor {\n')
            if self.behavior_tab.hide_while_typing_checkbox.isChecked():
                f.write('    hide-when-typing \n')
            else:
                f.write('    // hide-when-typing \n')
            if self.behavior_tab.inactive_enable_checkbox.isChecked():
                f.write(f'    hide-after-inactive-ms {self.behavior_tab.inactive_spinbox.value()}\n')
            else:
                f.write('    // hide-after-inactive-ms {self.behavior_tab.inactive_spinbox.value()}\n')

            f.write('}\n')

            # Screenshot path
            path = self.behavior_tab.screenshot_path_edit.text()
            if path:
                f.write(f'\nscreenshot-path "{path}"\n')

    def load_settings(self):
        """Load existing settings from input.kdl"""
        import re

        try:
            with open(self.config_path, 'r') as f:
                content = f.read()

            # Parse Appearance Settings
            self.appearance_tab.csd_checkbox.setChecked(
                '// prefer-no-csd' in content
            )
            value = re.search(r'zoom\s+([0-9]*\.?[0-9]+)', content)
            if value:
                self.appearance_tab.overview_spinbox.setValue(float(value.group(1)))

            self.appearance_tab.animations_enable_checkbox.setChecked(
            bool(re.search(r'animations\s*\{[^}]*\bon\b[^}]*\}', content)))

            value = re.search(r'slowdown\s+([0-9]*\.?[0-9]+)', content)
            self.appearance_tab.animations_spinbox.setValue(float(value.group(1)))

            value = re.search(r'gaps\s+(\d+)', content)
            self.appearance_tab.gaps_spinbox.setValue(int(value.group(1)))

            value = re.search(r'left\s+(\d+)', content)
            self.appearance_tab.struts_left_spin.setValue(int(value.group(1)))
            value = re.search(r'right\s+(\d+)', content)
            self.appearance_tab.struts_right_spin.setValue(int(value.group(1)))
            value = re.search(r'top\s+(\d+)', content)
            self.appearance_tab.struts_top_spin.setValue(int(value.group(1)))
            value = re.search(r'bottom\s+(\d+)', content)
            self.appearance_tab.struts_bottom_spin.setValue(int(value.group(1)))

            self.appearance_tab.focus_ring_enable_checkbox.setChecked(
            bool(re.search(r'focus-ring\s*\{[^}]*\bon\b[^}]*\}', content)))
            value = re.search(r'focus-ring\s*\{[^}]*width\s+(\d+)', content)
            self.appearance_tab.focus_ring_spinbox.setValue(int(value.group(1)))
            m = re.search(r'focus-ring\s*\{[^}]*active-color\s+"([^"]+)"', content)
            color_val = m.group(1)
            self.appearance_tab.current_color = color_val
            self.appearance_tab.update_color_button()

            self.appearance_tab.border_enable_checkbox.setChecked(
            bool(re.search(r'border\s*\{[^}]*\bon\b[^}]*\}', content)))
            value = re.search(r'border\s*\{[^}]*width\s+(\d+)', content)
            self.appearance_tab.border_spinbox.setValue(int(value.group(1)))
            m = re.search(r'border\s*\{[^}]*active-color\s+"([^"]+)"', content)
            color_val = m.group(1)

            self.appearance_tab.current_bordercolor = color_val
            self.appearance_tab.update_border_color_button()




            # Parse behavior settings
            self.behavior_tab.warp_mouse_to_focus_checkbox.setChecked(
                '// warp-mouse-to-focus' not in content
            )
            self.behavior_tab.focus_follows_mouse_checkbox.setChecked(
                '// focus-follows-mouse' not in content
            )
            self.behavior_tab.disable_power_key_checkbox.setChecked(
                '// disable-power-key-handling' not in content
            )
            self.behavior_tab.workspace_auto_back_forth_checkbox.setChecked(
                '// workspace-auto-back-and-forth' not in content
            )

            self.behavior_tab.hotkey_overlay_checkbox.setChecked(
                '// skip-at-startup' in content
            )

            self.behavior_tab.focus_request_checkbox.setChecked(
                '// honor-xdg-activation-with-invalid-serial ' not in content
            )

            self.behavior_tab.hide_while_typing_checkbox.setChecked(
                '// hide-when-typing ' not in content
            )
            self.behavior_tab.inactive_enable_checkbox.setChecked(
                '// hide-after-inactive-ms' not in content
            )

            value = re.search(r'hide-after-inactive-ms\s+(\d+)', content)
            if value:
                self.behavior_tab.inactive_spinbox.setValue(int(value.group(1)))

            match = re.search(r'gestures\s*\{\s*hot-corners\s*\{[^}]*//[^}]*\}\s*\}', content)
            if match:
                self.behavior_tab.hot_corners_checkbox.setChecked(False)
            else:
                self.behavior_tab.hot_corners_checkbox.setChecked(True)

            path = re.search(r'screenshot-path\s+"([^"]+)"', content)
            if path:
                self.behavior_tab.screenshot_path_edit.setText(path.group(1))

            # Parse mod key with radio buttons
            try:
                match = re.search(r'mod-key\s+"([^"]+)"', content)
                if match:
                    mod_key = match.group(1)
                    if mod_key == "Super":
                        self.behavior_tab.super_radio.setChecked(True)
                    elif mod_key == "Alt":
                        self.behavior_tab.alt_radio.setChecked(True)
                    elif mod_key == "Ctrl":
                        self.behavior_tab.ctrl_radio.setChecked(True)
            except Exception as e:
                print(f"Error parsing mod-key: {e}")

            # Touchpad settings
            self.touchpad_tab.tap_checkbox.setChecked(
                'tap' in content and '// tap' not in content
            )
            self.touchpad_tab.dwt_checkbox.setChecked(
                'dwt' in content and '// dwt' not in content
            )
            self.touchpad_tab.natural_scroll_checkbox.setChecked(
                'natural-scroll' in content and '// natural-scroll' not in content
            )
            self.touchpad_tab.drag_lock_checkbox.setChecked(
                'drag-lock' in content and '// drag-lock' not in content
            )
            self.touchpad_tab.disable_external_mouse_checkbox.setChecked(
                'disabled-on-external-mouse' in content and '// disabled-on-external-mouse' not in content
            )
            self.touchpad_tab.left_handed_checkbox.setChecked(
                'left-handed' in content and '// left-handed' not in content
            )
            try:
                # Touchpad acceleration speed and profile
                touchpad_match = re.search(r'touchpad\s*\{([^}]+)\}', content)
                if touchpad_match:
                    touchpad_content = touchpad_match.group(1)

                    # Parse acceleration speed
                    speed_match = re.search(r'accel-speed\s+(-?[\d.]+)', touchpad_content)
                    if speed_match:
                        self.touchpad_tab.accel_speed_spinbox.setValue(float(speed_match.group(1)))

                    # Parse acceleration profile
                    profile_match = re.search(r'accel-profile\s+"([^"]+)"', touchpad_content)
                    if profile_match:
                        profile_value = profile_match.group(1)
                        # Assuming you have a QComboBox for accel profile
                        index = self.touchpad_tab.accel_profile_combobox.findText(profile_value)
                        if index >= 0:
                            self.touchpad_tab.accel_profile_combobox.setCurrentIndex(index)

                    # Scroll factor
                    scroll_match = re.search(r'scroll-factor\s+([\d.]+)', touchpad_content)
                    if scroll_match:
                        self.touchpad_tab.scroll_factor_spinbox.setValue(float(scroll_match.group(1)))
            except:
                pass

                # Parse scroll method with radio buttons
            match = re.search(r'scroll-method\s+"([^"]+)"', content)
            if match:
                scroll_method = match.group(1)
                if scroll_method == "no-scroll":
                    self.touchpad_tab.no_scroll_radio.setChecked(True)
                elif scroll_method == "two-finger":
                    self.touchpad_tab.two_finger_radio.setChecked(True)
                elif scroll_method == "edge":
                    self.touchpad_tab.edge_radio.setChecked(True)
                elif scroll_method == "on-button-down":
                    self.touchpad_tab.button_radio.setChecked(True)

            # Mouse settings
            try:
                mouse_match = re.search(r'mouse\s*\{([^}]+)\}', content)
                if mouse_match:
                    mouse_content = mouse_match.group(1)

                    # Checkboxes within mouse block
                    self.mouse_tab.natural_scroll_checkbox.setChecked(
                        'natural-scroll' in mouse_content and '// natural-scroll' not in mouse_content
                    )
                    self.mouse_tab.left_handed_checkbox.setChecked(
                        'left-handed' in mouse_content and '// left-handed' not in mouse_content
                    )
                    self.mouse_tab.middle_emulation_checkbox.setChecked(
                        'middle-emulation' in mouse_content and '// middle-emulation' not in mouse_content
                    )

                    # Mouse acceleration speed
                    speed_match = re.search(r'accel-speed\s+(-?[\d.]+)', mouse_content)
                    if speed_match:
                        self.mouse_tab.accel_speed_spinbox.setValue(float(speed_match.group(1)))

                    # Mouse acceleration profile
                    profile_match = re.search(r'accel-profile\s+"([^"]+)"', mouse_content)
                    if profile_match:
                        profile_value = profile_match.group(1)
                        index = self.mouse_tab.accel_profile_combobox.findText(profile_value)
                        if index >= 0:
                            self.mouse_tab.accel_profile_combobox.setCurrentIndex(index)

                    # Scroll factor
                    scroll_match = re.search(r'scroll-factor\s+([\d.]+)', mouse_content)
                    if scroll_match:
                        self.mouse_tab.scroll_factor_spinbox.setValue(float(scroll_match.group(1)))
            except:
                pass

            # Keyboard settings
            self.keyboard_tab.numlock_checkbox.setChecked(
                'numlock' in content and '// numlock' not in content
            )

            match = re.search(r'repeat-delay\s+(\d+)', content)
            if match:
                self.keyboard_tab.repeat_delay_spinbox.setValue(int(match.group(1)))

            match = re.search(r'repeat-rate\s+(\d+)', content)
            if match:
                self.keyboard_tab.repeat_rate_spinbox.setValue(int(match.group(1)))

            # Track layout
            match = re.search(r'track-layout\s+"([^"]+)"', content)
            if match:
                track_layout = match.group(1)
                index = self.keyboard_tab.track_layout_combobox.findText(track_layout)
                if index >= 0:
                        self.keyboard_tab.track_layout_combobox.setCurrentIndex(index)

            try:
                # XKB layout
                xkb_match = re.search(r'xkb\s*{.*?layout\s+"([^"]+)"', content, re.DOTALL)
                if xkb_match:
                    self.keyboard_tab.layout_edit.setText(xkb_match.group(1))
            except:
                pass

            try:
                # XKB Variant
                variant_match = re.search(r'xkb\s*{.*?variant\s+"([^"]+)"', content, re.DOTALL)
                if variant_match:
                    self.keyboard_tab.variant_edit.setText(variant_match.group(1))
            except:
                pass

            try:
                # XKB options
                options_match = re.search(r'xkb\s*{.*?options\s+"([^"]+)"', content, re.DOTALL)
                if options_match:
                    self.keyboard_tab.options_edit.setText(options_match.group(1))
            except:
                pass

            try:
                # XKB model
                model_match = re.search(r'xkb\s*{.*?model\s+"([^"]+)"', content, re.DOTALL)
                if model_match:
                    self.keyboard_tab.model_edit.setText(model_match.group(1))
            except:
                pass

            try:
                # XKB file
                file_match = re.search(r'xkb\s*{.*?file\s+"([^"]+)"', content, re.DOTALL)
                if file_match:
                    self.keyboard_tab.file_edit.setText(file_match.group(1))
            except:
                pass
        except FileNotFoundError:
            # If file doesn't exist, use defaults
            print(f"No existing config file found at {self.config_path}, using defaults")
        except Exception as e:
            print(f"Error loading configuration: {e}")
